services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_PORT}
    ports:
      - "${FASTAPI_PORT}:8000"
    volumes:
      - ./data:/data            # Monta carpeta para CSVs
    env_file:
      - .env

  simulator:
    build: .
    command: python simulator.py
    depends_on:
      - fastapi
    env_file:
      - .env

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    ports:
      - "${DOCKER_INFLUXDB_INIT_PORT}:8086"
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    ports:
      - "${GRAFANA_PORT}:3000"

volumes:
  grafana-storage:
  influxdb-storage:
