{
 "title": "MONITOREAR PACIENTES",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "id_Paciente", "query": "1,2,3,4,5,6,7,8,9,10" },
   { "name": "actividad", "query": "reposo,moderado,ligero" },
   { "name": "estado_animo", "query": "cansado,estresado,feliz,neutro" }
  ]
 },
 "panels": [
  {
   "title": "RITMO CARDIACO PACIENTES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"deusto-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"salud\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ritmo_cardiaco\")\r\n  |> filter(fn: (r) => r[\"paciente_id\"] == \"${id_Paciente}\")\r\n  |> filter(fn: (r) => r[\"actividad\"] == \"${actividad}\")\r\n  |> filter(fn: (r) => r[\"estado_animo\"] == \"${estado_animo}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TEMPERATURA EN REPOSO PACIENTES",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"deusto-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"salud\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\r\n  |> filter(fn: (r) => r[\"paciente_id\"] == \"${id_Paciente}\")\r\n  |> filter(fn: (r) => r[\"actividad\"] == \"${actividad}\")\r\n  |> group(columns: [])           // <--- agrupar todo junto, sin etiquetas\r\n  |> mean()\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "FRECUENCIA RESPIRATORIA PACIENTES (SPO2)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"deusto-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"salud\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"frecuencia_respiratoria\")\r\n  |> filter(fn: (r) => r[\"paciente_id\"] == \"${id_Paciente}\")\r\n  |> filter(fn: (r) => r[\"actividad\"] == \"${actividad}\")\r\n  |> filter(fn: (r) => r[\"estado_animo\"] == \"${estado_animo}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "COMPARACIÓN FRECUENCIA RESPIRATORIA PACIENTES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"deusto-bucket\")\r\n  |> range(start: -1h)  // últimos 1 hora, puedes usar variables también\r\n  |> filter(fn: (r) => r._measurement == \"salud\" and r._field == \"spo2\")\r\n  |> group(columns: [\"paciente_id\"])\r\n  |> aggregateWindow(every: 5m, fn: mean)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PASOS POR PACIENTES ULTIMAS 3 HORAS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"deusto-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"salud\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pasos\")\r\n  |> filter(fn: (r) => r[\"actividad\"] == \"${actividad}\")\r\n  |> aggregateWindow(every: 3h, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"paciente_id\"], valueColumn: \"_value\")\r\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}